(source (official ppx))
(config username "Paul TSNOBILADZE")
(config project_name inline-test-ppx)
(config npm_username dialohq)
(config github_username dialohq)
(config project_description "A PPX to write inline tests in rescript")
(config package_manager Esy)
(config ci_cd Github)
(config syntax OCaml)
(config project_snake inline_test_ppx)
(config project_slug inline-test-ppx)
(config test_framework Alcotest)
